import { compositionsById } from "@workspace/compositions/registry";
import type { CompositionCategory } from "@workspace/compositions/schema";
import { tool } from "ai";
import { z } from "zod";
import {
  isAgentVisible,
  KNOWN_CATEGORIES,
  listScenesInCategory,
} from "./catalog";
import { TEMPLATES, templateDurationInFrames } from "./templates";

/**
 * Trim a defaultProps payload so the agent sees the SHAPE without the
 * bulk. Long strings get truncated with a remaining-char hint; long
 * arrays get the first 3 items plus a remaining-count hint. The agent
 * can still infer the schema from the keys + sample values, but a
 * single getSceneDetails response that was 3,000+ tokens (e.g.
 * GaiaScenario) collapses to a few hundred.
 */
function trimForAgent(value: unknown, depth = 0): unknown {
  if (depth > 6) return "[deep]";
  if (typeof value === "string") {
    if (value.length <= 200) return value;
    return `${value.slice(0, 180)}…[+${value.length - 180} chars truncated]`;
  }
  if (Array.isArray(value)) {
    if (value.length <= 3) return value.map((v) => trimForAgent(v, depth + 1));
    return [
      ...value.slice(0, 3).map((v) => trimForAgent(v, depth + 1)),
      `…[+${value.length - 3} more items, same shape]`,
    ];
  }
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = trimForAgent(v, depth + 1);
    }
    return out;
  }
  return value;
}

/**
 * Two-track tool surface for the studio agent:
 *
 *   PRIMARY (one-shot generation): `buildProject` takes a complete Project
 *   JSON matching the studio's import schema and loads it via LOAD_PROJECT.
 *   This is what the agent calls when the user asks for a fresh video.
 *
 *   SURGICAL (edits): `addClip`, `updateClipProps`, `updateClipStyle`,
 *   `updateClipDuration`, `deleteClip`, `clearProject`, `listClips`. These
 *   mutate the existing timeline one operation at a time. The agent
 *   reaches for them when the user says "tweak", "swap", "remove that",
 *   etc. — preserving the user's manual changes.
 *
 *   DISCOVERY: `listScenes` and `getSceneDetails` exist as fallback for
 *   the few cases where the inline catalog in the system prompt isn't
 *   enough (or when the user adds a new composition mid-session).
 *
 * Server-executed tools have an `execute` here; client-executed tools
 * have only a schema and run inside AgentPanel's `onToolCall` so they
 * can dispatch into the studio reducer.
 */

// Project JSON schema — mirrors `parseProjectJson` in features/studio/lib/project-io.ts.
const ClipStyleSchema = z
  .object({
    background: z.string().optional(),
    color: z.string().optional(),
    fontFamily: z.string().optional(),
    accent: z.string().optional(),
  })
  .partial();

const SceneTransitionSchema = z
  .object({
    kind: z.string(),
    durationInFrames: z.number().int().min(0).optional(),
  })
  .passthrough();

const ClipSchema = z.object({
  id: z
    .string()
    .min(1)
    .describe(
      "Stable unique id within the project. Use kebab/uuid style — generated by the agent.",
    ),
  compositionId: z
    .string()
    .min(1)
    .describe("PascalCase composition id from the catalog (e.g. 'TitlePopup')"),
  props: z
    .record(z.string(), z.unknown())
    .describe(
      "FULL props object. Start from the composition's defaultProps in the catalog and override only the fields you want to change.",
    ),
  durationInFrames: z.number().int().min(15).optional(),
  style: ClipStyleSchema.optional(),
  transition: SceneTransitionSchema.optional(),
});

const ProjectSchema = z.object({
  fps: z.number().int().min(1),
  width: z.number().int().min(1),
  height: z.number().int().min(1),
  clips: z.array(ClipSchema).min(1),
  defaultTransition: SceneTransitionSchema.optional(),
});

export const tools = {
  // ───── PRIMARY: template-driven generation ────────────────────────────
  // Templates pin duration + narrative arc + slot categories so the
  // agent's job shrinks to "pick a scene per slot". This makes "20s
  // ask becomes 8s build" structurally impossible — slot durations
  // are fixed in the template definition.
  listTemplates: tool({
    description:
      "Returns every video template — name, description, whenToUse, total duration in seconds, and the ordered slot list (each slot has a fixed category, fixed duration, and a role description). ALWAYS call this first for fresh video asks. Most user briefs fit a template; templates guarantee the right duration and a coherent narrative.",
    inputSchema: z.object({}),
    execute: async () => ({
      templates: TEMPLATES.map((t) => ({
        id: t.id,
        name: t.name,
        description: t.description,
        whenToUse: t.whenToUse,
        totalDurationFrames: templateDurationInFrames(t),
        totalDurationSeconds:
          Math.round((templateDurationInFrames(t) / t.fps) * 10) / 10,
        fps: t.fps,
        width: t.width,
        height: t.height,
        slots: t.slots.map((s) => ({
          id: s.id,
          role: s.role,
          category: s.category,
          durationInFrames: s.durationInFrames,
          description: s.description,
        })),
      })),
    }),
  }),

  buildFromTemplate: tool({
    description:
      "Build a project by filling every slot of a template. Duration + narrative arc + transition are pinned by the template. Workflow: call listTemplates → pick one → for each slot call listScenesInCategory(slot.category) → call getSceneDetails on the scenes you want → submit slotPicks here (one pick per slot). The picked scene must belong to the slot's category. Optionally set a project-wide `style` (background/text/accent/font) that applies to every non-brand-locked clip for visual consistency.",
    inputSchema: z.object({
      templateId: z.string().describe("Template id from listTemplates."),
      slotPicks: z
        .array(
          z.object({
            slotId: z.string(),
            compositionId: z.string(),
            props: z.record(z.string(), z.unknown()),
          }),
        )
        .describe(
          "EXACTLY one pick per slot. slotId must match a slot in the template; compositionId must belong to that slot's category.",
        ),
      style: z
        .object({
          backgroundColor: z.string().optional(),
          textColor: z.string().optional(),
          fontFamily: z.string().optional(),
          accentColor: z.string().optional(),
        })
        .optional()
        .describe(
          "Optional palette applied to every non-brand-locked clip so the project has a consistent visual look. Brand-locked scenes (Slack, WhatsApp, etc.) ignore this.",
        ),
    }),
    // No execute — runs client-side in AgentPanel.onToolCall (validates
    // slot/category match, then assembles a Project and dispatches
    // LOAD_PROJECT).
  }),

  // ───── FALLBACK: free-form generation ─────────────────────────────────
  buildProject: tool({
    description:
      "Replace the entire timeline with a freeform project. Use ONLY when no template fits the user's brief (unusual length, unusual arc, very specific scene order the user requested). Templates are preferred — they guarantee duration and narrative. Atomic: either the whole project loads or nothing does.",
    inputSchema: z.object({
      project: ProjectSchema.describe(
        "The complete Project JSON. Must include fps, width, height, and a non-empty clips array. Each clip needs id, compositionId, and props.",
      ),
    }),
    // No execute — runs client-side in AgentPanel.onToolCall.
  }),

  // ───── DISCOVERY (category → scenes → details funnel) ────────────────
  // The system prompt lists categories. The agent calls
  // `listScenesInCategory` to drill in, then `getSceneDetails` for the
  // few scenes it wants to use. This keeps the prompt constant-size as
  // the registry grows.
  listScenesInCategory: tool({
    description:
      "Returns every scene in a category as `{ id, title, description, durationInFrames, fps, width, height, brandLocked }`. Call this for each category that fits the user's brief; then call getSceneDetails for the scenes you actually want to build with.",
    inputSchema: z.object({
      category: z
        .enum(
          KNOWN_CATEGORIES as [CompositionCategory, ...CompositionCategory[]],
        )
        .describe(
          "One of the category slugs from the prompt: text, social, data, devtools, marketing, layout, captions, media.",
        ),
    }),
    execute: async ({ category }) => ({
      category,
      scenes: listScenesInCategory(category),
    }),
  }),

  getSceneDetails: tool({
    description:
      "Returns the trimmed defaultProps for one composition (long strings shortened, long arrays clipped to first 3 items — the SHAPE is preserved). Call this for every scene you plan to use in buildProject so your props match the schema. Drop this into clip.props as your starting point and override only what changes.",
    inputSchema: z.object({
      compositionId: z.string(),
    }),
    execute: async ({ compositionId }) => {
      if (!isAgentVisible(compositionId)) {
        return {
          error: `Unknown composition id: ${compositionId}. Use listScenesInCategory to discover available scenes.`,
        };
      }
      const info = compositionsById[compositionId];
      if (!info) return { error: `Unknown composition id: ${compositionId}` };
      return {
        id: info.id,
        title: info.title,
        description: info.description,
        category: info.category,
        brandLocked: info.brandMode === "locked",
        defaultDurationFrames: info.durationInFrames,
        // Trimmed payload — full defaultProps can be 3–4k tokens for
        // heavy scenes (chat scripts, terminal lines). The agent gets
        // the schema shape + sample values, not the bulk.
        defaultProps: trimForAgent(info.defaultProps),
      };
    },
  }),

  // ───── SURGICAL edits (client-executed) ───────────────────────────────
  listClips: tool({
    description:
      "Read the current timeline. Returns clips in order with id, compositionId, durationInFrames, props, and style. Call this before any surgical edit so you reference the right clipIds.",
    inputSchema: z.object({}),
  }),

  clearProject: tool({
    description: "Remove every clip from the timeline.",
    inputSchema: z.object({}),
  }),

  addClip: tool({
    description:
      "Append a new clip to the timeline. Returns the new clipId. Prefer buildProject for full-project generation; use addClip only for incremental additions to an existing timeline.",
    inputSchema: z.object({
      compositionId: z.string(),
    }),
  }),

  updateClipProps: tool({
    description:
      "Replace a clip's props with new values. Pass the FULL props object — this is a replace, not a patch. Look up the clip's current props with listClips first and merge.",
    inputSchema: z.object({
      clipId: z.string(),
      props: z.record(z.string(), z.unknown()),
    }),
  }),

  updateClipStyle: tool({
    description:
      "Change a clip's universal style (background, color, fontFamily, accent). Any omitted field is left untouched. Empty string clears the override. No effect on brand-locked scenes.",
    inputSchema: z.object({
      clipId: z.string(),
      background: z.string().optional(),
      color: z.string().optional(),
      fontFamily: z.string().optional(),
      accent: z.string().optional(),
    }),
  }),

  updateClipDuration: tool({
    description:
      "Set how many frames a clip plays for. 30fps → 90 frames = 3 seconds.",
    inputSchema: z.object({
      clipId: z.string(),
      durationInFrames: z.number().int().min(15),
    }),
  }),

  deleteClip: tool({
    description: "Remove one clip from the timeline by id.",
    inputSchema: z.object({
      clipId: z.string(),
    }),
  }),
};

export type AgentTools = typeof tools;
