#!/usr/bin/env node
/**
 * Reads every composition's source files and emits a static TypeScript
 * module mapping `<id>` → `{ component, meta }` source strings. The Docs
 * page imports this file to render the Source block client-side without
 * touching Node fs at runtime.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..", "..");
const compositionsDir = join(repoRoot, "apps", "remotion", "src", "compositions");

const dirs = readdirSync(compositionsDir).filter((d) => {
  const full = join(compositionsDir, d);
  return statSync(full).isDirectory() && /^[A-Z]/.test(d);
});

const entries = [];
for (const dir of dirs) {
  const compFile = join(compositionsDir, dir, `${dir}.tsx`);
  const metaFile = join(compositionsDir, dir, "meta.ts");
  let component = "";
  let meta = "";
  try {
    component = readFileSync(compFile, "utf-8");
  } catch {
    continue; // skip wrappers that don't have a same-named .tsx
  }
  try {
    meta = readFileSync(metaFile, "utf-8");
  } catch {
    meta = "";
  }
  entries.push({ id: dir, component, meta });
}

const banner = `// AUTO-GENERATED by scripts/generate-sources.mjs. Do not edit by hand.\n// Re-run: bun run --cwd apps/web sources\n// biome-ignore-all lint/suspicious/noArrayIndexKey: source code stored as strings; lints don't apply\n// biome-ignore-all lint/suspicious/noTemplateCurlyInString: source code stored as strings; lints don't apply\n\n`;
const body = entries
  .map(
    (e) => `  ${JSON.stringify(e.id)}: {\n    component: ${JSON.stringify(e.component)},\n    meta: ${JSON.stringify(e.meta)},\n  },`,
  )
  .join("\n");

const out = `${banner}export type CompositionSource = {\n  component: string;\n  meta: string;\n};\n\nexport const compositionSources: Record<string, CompositionSource> = {\n${body}\n};\n`;

const target = join(repoRoot, "apps", "web", "lib", "generated-sources.ts");
writeFileSync(target, out, "utf-8");
console.log(`Wrote ${entries.length} source entries → ${target}`);
