#!/usr/bin/env node
/**
 * Reads every composition's source files and emits a static TypeScript
 * module mapping `<id>` → `{ component, meta }` source strings. The Docs
 * page imports this file to render the Source block client-side without
 * touching Node fs at runtime.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..", "..");
const remotionSrc = join(repoRoot, "apps", "remotion", "src");
const compositionsDir = join(remotionSrc, "compositions");

// Only compositions that are actually registered get a source entry: anything
// imported from `compositions/<path>/meta` in registry.ts, plus anything the
// render lookup maps (componentsBase.ts / components.ts — this is what keeps
// the un-registered wrappers PhoneFrame / LaptopFrame exportable). Folders
// that only exist as building blocks for a dispatcher (the Text*/Title*
// variants behind `Text`) are skipped so they don't bloat the bundle.
const registered = new Set();
for (const file of ["registry.ts", "componentsBase.ts", "components.ts"]) {
  const src = readFileSync(join(remotionSrc, file), "utf-8");
  for (const m of src.matchAll(/from "\.\/compositions\/([^"]+)\/[^"/]+"/g)) {
    registered.add(m[1]);
  }
}

const entries = [];

// Collect `<Name>/<Name>.tsx` composition folders. A folder without a
// same-named component (e.g. the `backgrounds/` grouping dir) is recursed into
// one level so grouped categories are picked up too. Underscore/dot-prefixed
// dirs (helpers like `_chat-demo`) are skipped.
function collect(dir, prefix = "") {
  for (const name of readdirSync(dir)) {
    if (name.startsWith("_") || name.startsWith(".")) continue;
    const full = join(dir, name);
    if (!statSync(full).isDirectory()) continue;
    let component = "";
    try {
      component = readFileSync(join(full, `${name}.tsx`), "utf-8");
    } catch {
      collect(full, `${prefix}${name}/`); // grouping dir — descend one level
      continue;
    }
    if (!registered.has(`${prefix}${name}`)) continue;
    let meta = "";
    try {
      meta = readFileSync(join(full, "meta.ts"), "utf-8");
    } catch {
      meta = "";
    }
    entries.push({
      id: name,
      modulePath: `${prefix}${name}/${name}`,
      component,
      meta,
    });
  }
}

collect(compositionsDir);

const banner = `// AUTO-GENERATED by scripts/generate-sources.mjs. Do not edit by hand.\n// Re-run: bun run --cwd apps/web sources\n// biome-ignore-all lint/suspicious/noArrayIndexKey: source code stored as strings; lints don't apply\n// biome-ignore-all lint/suspicious/noTemplateCurlyInString: source code stored as strings; lints don't apply\n\n`;
const body = entries
  .map(
    (e) => `  ${JSON.stringify(e.id)}: {\n    component: ${JSON.stringify(e.component)},\n    meta: ${JSON.stringify(e.meta)},\n  },`,
  )
  .join("\n");

const out = `${banner}export type CompositionSource = {\n  component: string;\n  meta: string;\n};\n\nexport const compositionSources: Record<string, CompositionSource> = {\n${body}\n};\n`;

const target = join(repoRoot, "apps", "web", "lib", "generated-sources.ts");
writeFileSync(target, out, "utf-8");
console.log(`Wrote ${entries.length} source entries → ${target}`);

// Preview loader map: one static import() literal per composition, so each
// compiles as its own on-demand chunk. The wildcard import this replaces
// (import(`…/${modulePath}`)) made Turbopack build a context module over the
// whole compositions tree — every module compiled the first time any preview
// mounted, which wedged dev for minutes.
const loaderBody = entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.modulePath)}: () =>\n    import(${JSON.stringify(`@workspace/compositions/compositions/${e.modulePath}`)}),`,
  )
  .join("\n");

const loaderOut = `${banner}export const previewLoaders: Record<\n  string,\n  () => Promise<Record<string, unknown>>\n> = {\n${loaderBody}\n};\n`;

const loaderTarget = join(repoRoot, "apps", "web", "lib", "preview-loaders.ts");
writeFileSync(loaderTarget, loaderOut, "utf-8");
console.log(`Wrote ${entries.length} preview loaders → ${loaderTarget}`);
