"use client";

import { useChat } from "@ai-sdk/react";
import { Cancel01Icon, RefreshIcon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import type { Project } from "@workspace/compositions/project";
import { compositions } from "@workspace/compositions/registry";
import { Button } from "@workspace/ui/components/button";
import { Composer, type MentionItem } from "@workspace/ui/components/composer";
import { WaveSpinner } from "@workspace/ui/components/wave-spinner";
import { lastAssistantMessageIsCompleteWithToolCalls } from "ai";
import Image from "next/image";
import { useEffect, useMemo, useRef, useState } from "react";
import { isAgentVisible } from "@/lib/agent/catalog";
import type { StudioAction } from "../state/reducer";
import { runClientTool } from "./agent-panel/client-tools";
import { EmptyState } from "./agent-panel/empty-state";
import { humanizeAgentError } from "./agent-panel/error";
import { MessageBubble } from "./agent-panel/message-bubble";
import { ThinkingPhrase } from "./agent-panel/thinking-phrase";

type Props = {
  project: Project;
  dispatch: React.Dispatch<StudioAction>;
  onClose: () => void;
  /** The clip currently selected in the timeline/inspector, if any. Lets the
   *  agent target it directly when the user @mentions its composition. */
  selectedClip?: { id: string; compositionId: string } | null;
};

// Cap on how many times the SDK will auto-continue per user message.
// Surgical edits ("add a tweet card") need: listClips → listScenesInCategory
// → getSceneDetails → addClip → updateClipProps — that's 5 tool turns
// before the terminal-tool short-circuit fires on addClip/updateClipProps.
// Set generously so multi-step edits aren't truncated mid-flow; the
// terminal-tool short-circuit ends the loop early on successful builds.
const MAX_AUTO_CONTINUATIONS_PER_USER_MESSAGE = 12;

const TERMINAL_TOOL_TYPES = new Set([
  "tool-buildProject",
  "tool-clearProject",
  "tool-addClip",
  "tool-deleteClip",
  "tool-updateClipProps",
  "tool-updateClipStyle",
  "tool-updateClipDuration",
]);

export function AgentPanel({
  project,
  dispatch,
  onClose,
  selectedClip,
}: Props) {
  // Keep the latest project in a ref so onToolCall (closed over at mount)
  // always sees current clips/ids instead of a stale snapshot. Assigned during
  // render rather than in an effect — the value is only ever read later, in
  // async callbacks, so there's no need to wait for a commit.
  const projectRef = useRef(project);
  projectRef.current = project;

  // Same trick for brand kit — the chat transport (memoized once) reads
  // the latest brand kit from this ref so updates flow into the next
  // chat request without recreating useChat (which would wipe history).
  const brandKitRef = useRef(project.brandKit);
  brandKitRef.current = project.brandKit;

  // The @mention picker offers every agent-visible composition; selecting one
  // inserts `@<id>` into the message. Built once — the registry is static.
  const mentionItems = useMemo<MentionItem[]>(
    () =>
      compositions
        .filter((c) => isAgentVisible(c.id))
        .map((c) => ({ id: c.id, label: c.title, hint: c.category })),
    [],
  );

  // Latest @mention ids + selected clip, read at send time (refs so the
  // memoized chat transport always sees current values — same trick as
  // brandKit above).
  const mentionsRef = useRef<string[]>([]);
  const selectedClipRef = useRef(selectedClip ?? null);
  selectedClipRef.current = selectedClip ?? null;

  // Tracks how many times the SDK has auto-continued since the user
  // last sent a message. We compare to the cap inside
  // `sendAutomaticallyWhen` to break runaway loops.
  const autoContinuationCount = useRef(0);

  // Latch: flips true the moment a terminal build/edit lands ok in the
  // CURRENT user turn, and from then on blocks every auto-continuation —
  // even if the build scrolled out of the last message. Once it's built the
  // turn is over; the closing recap is synthesized in MessageBubble, not
  // generated by the model. Reset on each send().
  const builtThisTurn = useRef(false);

  const {
    messages,
    sendMessage,
    status,
    stop,
    error,
    regenerate,
    addToolResult,
  } = useChat({
    sendAutomaticallyWhen: (args) => {
      const ready = lastAssistantMessageIsCompleteWithToolCalls(args);
      if (!ready) return false;

      // Hard stop: a terminal build/edit already landed earlier in this
      // turn. The goal is done — refuse every further continuation so the
      // model can't drift into an open-ended polish loop (transitions,
      // effects) and burn turns toward the cap.
      if (builtThisTurn.current) return false;

      // Terminal-tool short-circuit: the last assistant message includes a
      // successful build (or clear/edit) result — that IS the final action,
      // so stop. We do NOT grant a continuation for a summary turn:
      // gpt-5-mini almost always skips it (it spends its words on the
      // opener), so the turn just burns a call on an empty response. The
      // closing recap is synthesized deterministically in MessageBubble from
      // the build result instead. Latch `builtThisTurn` so the rule still
      // holds if the build scrolls out of the last message.
      const lastMsg = args.messages[args.messages.length - 1];
      if (lastMsg?.role === "assistant") {
        const hasTerminalResult = lastMsg.parts.some((p) => {
          if (!TERMINAL_TOOL_TYPES.has(p.type)) return false;
          const out = (p as { output?: unknown }).output;
          return (
            typeof out === "object" &&
            out !== null &&
            (out as { ok?: unknown }).ok === true
          );
        });
        if (hasTerminalResult) {
          builtThisTurn.current = true;
          return false;
        }
      }

      if (
        autoContinuationCount.current >= MAX_AUTO_CONTINUATIONS_PER_USER_MESSAGE
      ) {
        return false;
      }
      autoContinuationCount.current += 1;
      return true;
    },
    onToolCall: async ({ toolCall }) => {
      const name = toolCall.toolName;
      const input = toolCall.input as Record<string, unknown>;
      try {
        const output = runClientTool(name, input, projectRef, dispatch);
        if (output === undefined) return; // server-executed tool, ignore
        await addToolResult({
          tool: name as never,
          toolCallId: toolCall.toolCallId,
          output: output as never,
        });
      } catch (err) {
        await addToolResult({
          tool: name as never,
          toolCallId: toolCall.toolCallId,
          output: {
            error: err instanceof Error ? err.message : String(err),
          } as never,
        });
      }
    },
  });

  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  const lastMessage = messages[messages.length - 1];
  const lastIsAssistant = lastMessage?.role === "assistant";
  const hasPendingTool =
    lastMessage?.role === "assistant" &&
    lastMessage.parts.some(
      (p) =>
        p.type.startsWith("tool-") &&
        (p as { output?: unknown }).output === undefined,
    );
  const hasSuccessfulTerminal =
    lastMessage?.role === "assistant" &&
    lastMessage.parts.some((p) => {
      if (!TERMINAL_TOOL_TYPES.has(p.type)) return false;
      const out = (p as { output?: unknown }).output;
      return (
        typeof out === "object" &&
        out !== null &&
        (out as { ok?: unknown }).ok === true
      );
    });
  const hasAnyToolCall =
    lastMessage?.role === "assistant" &&
    lastMessage.parts.some((p) => p.type.startsWith("tool-"));
  // Settled = genuinely done: nothing still waiting on a result, and either
  // a terminal build/edit landed or the assistant replied with plain text
  // and never called a tool at all. Anything else — e.g. listClips just
  // resolved but addClip/buildProject hasn't run — means a continuation
  // is about to fire automatically, even though the HTTP response that
  // carried listClips's result has already closed.
  const lastAssistantSettled =
    lastIsAssistant &&
    !hasPendingTool &&
    (hasSuccessfulTerminal || !hasAnyToolCall);

  // A request is on the wire (or about to be).
  const requestInFlight = status === "submitted" || status === "streaming";

  // The gap AFTER an HTTP response carrying a non-terminal tool result
  // closes (status → "ready") but BEFORE the auto-continuation fires.
  // Normally a few ms; if a continuation never comes (cap hit, or
  // `sendAutomaticallyWhen` returns false) the watchdog below releases us.
  const waitingOnContinuation =
    status === "ready" && lastIsAssistant && !lastAssistantSettled;

  // Either of these means "the agent should still be working".
  const busy = requestInFlight || waitingOnContinuation;

  // ONE watchdog across EVERY busy state — both an in-flight stream and the
  // continuation gap. `status` can get stuck at "streaming" (response never
  // cleanly closes) just as easily as it can lie during the gap, so we
  // can't trust it alone in either case. The timer resets on every new
  // streamed part, so an actively-streaming response keeps it disarmed; it
  // only fires after a long stretch of TOTAL silence — a genuinely hung
  // stream or a continuation that never starts. The window is deliberately
  // generous: a reasoning model can legitimately go quiet for several
  // seconds between steps, and a 4s window (the old value) mistook those
  // pauses for a hang and hid the loader mid-build.
  const [forceIdle, setForceIdle] = useState(false);
  const lastActivitySig = useRef<string>("");
  useEffect(() => {
    const sig = messages
      .map((m) => `${m.id}:${m.parts.length}:${JSON.stringify(m.parts).length}`)
      .join("|");
    if (sig !== lastActivitySig.current) {
      lastActivitySig.current = sig;
      setForceIdle(false);
    }
    if (!busy) return;
    const t = setTimeout(() => setForceIdle(true), 15000);
    return () => clearTimeout(t);
  }, [messages, busy]);

  const isBusy = busy && !forceIdle && !error;

  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [messages, status]);

  async function send(text: string) {
    const trimmed = text.trim();
    if (!trimmed) return;
    // If a build is still in flight, cancel it before queuing the new
    // message. Without this the new sendMessage call gets dropped by
    // useChat ("can't send while not ready") and the user's input
    // disappears into the void.
    if (isBusy) {
      await stop();
    }
    autoContinuationCount.current = 0;
    builtThisTurn.current = false;
    // Piggyback the project's brandKit + any @mentioned components + the
    // selected clip so the server can switch into focused-component mode and
    // append the right context. Refs always point at the latest values, so
    // edits show up on the very next send.
    sendMessage(
      { text: trimmed },
      {
        body: {
          brandKit: brandKitRef.current,
          mentions: mentionsRef.current,
          selectedClip: selectedClipRef.current,
        },
      },
    );
    mentionsRef.current = [];
    setInput("");
  }

  return (
    <aside className="relative flex h-full w-full flex-col overflow-hidden border-r border-border bg-background">
      {/*
        Ambient hero — the wildflower-sunset artwork washes in at the top and
        melts into the dark panel. Only present on the empty state; the moment
        the user sends a brief and the conversation begins, it unmounts so the
        chat reads clean.
      */}
      {messages.length === 0 ? (
        <div
          aria-hidden
          className="pointer-events-none absolute inset-x-0 top-0 z-0 h-72 bg-cover bg-center opacity-[0.55]"
          style={{
            backgroundImage: "url(/background.png)",
            maskImage:
              "linear-gradient(to bottom, rgba(0,0,0,0.95) 0%, rgba(0,0,0,0.5) 45%, transparent 100%)",
            WebkitMaskImage:
              "linear-gradient(to bottom, rgba(0,0,0,0.95) 0%, rgba(0,0,0,0.5) 45%, transparent 100%)",
          }}
        />
      ) : null}

      <div
        className={`relative z-10 flex items-center justify-between border-b px-4 py-3 ${
          messages.length === 0
            ? "border-white/10 bg-background/30 backdrop-blur-md"
            : "border-border"
        }`}
      >
        <div className="flex items-center gap-2">
          <Image
            src="/logo.png"
            alt=""
            aria-hidden
            width={24}
            height={24}
            className="size-6 shrink-0 object-contain"
          />
          <div>
            <p className="text-sm font-medium text-foreground">Agent</p>
            <p className="text-[11px] text-muted-foreground">
              Describe it — it builds the timeline
            </p>
          </div>
        </div>
        <Button
          variant="ghost"
          size="icon"
          onClick={onClose}
          className="size-6"
        >
          <HugeiconsIcon icon={Cancel01Icon} className="size-3.5" />
        </Button>
      </div>

      <div
        ref={scrollRef}
        className="relative z-10 min-h-0 flex-1 overflow-y-auto px-4 py-4"
      >
        {messages.length === 0 ? (
          <EmptyState onPick={send} />
        ) : (
          <ul className="space-y-3">
            {messages.map((m, i) => {
              const isLast = i === messages.length - 1;
              return (
                <MessageBubble
                  key={m.id}
                  message={m}
                  isStreaming={
                    status === "streaming" && isLast && m.role === "assistant"
                  }
                />
              );
            })}
            {/*
              ONE persistent activity indicator. Lives at the bottom of
              the list and stays visible the entire time the chat is
              busy — never flickers or moves position. Phrase pool
              switches based on whether an assistant message has started
              forming yet.
            */}
            {isBusy ? (
              <li className="flex items-center gap-2.5 py-1">
                <WaveSpinner
                  size="md"
                  pattern="line"
                  dotShape="circle"
                  animation="horizontal"
                  color="primary"
                />
                <ThinkingPhrase
                  pool={
                    lastMessage?.role === "assistant" ? "working" : "planning"
                  }
                />
              </li>
            ) : null}
            {error ? (
              <li className="flex flex-col gap-2 rounded-md border border-destructive/30 bg-destructive/10 p-3 text-[12px] text-destructive">
                <span className="font-medium">Agent error</span>
                <span className="whitespace-pre-wrap break-words font-mono text-[11px] leading-relaxed opacity-90">
                  {humanizeAgentError(error)}
                </span>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() =>
                    regenerate({ body: { brandKit: brandKitRef.current } })
                  }
                  className="h-7 self-start"
                >
                  <HugeiconsIcon icon={RefreshIcon} className="size-3" />
                  Retry
                </Button>
              </li>
            ) : null}
          </ul>
        )}
      </div>

      <div className="border-t border-border p-3">
        <Composer
          value={input}
          onChange={setInput}
          onSubmit={send}
          onStop={() => stop()}
          mentionItems={mentionItems}
          onMentionsChange={(ids) => {
            mentionsRef.current = ids;
          }}
          isLoading={isBusy && input.trim().length === 0}
          placeholder={
            isBusy
              ? "Compose your next message — Stop to send now…"
              : "Describe the video you want…"
          }
        />
        <p className="mt-2 text-[10px] text-muted-foreground/70">
          Enter to send · Shift+Enter for newline
        </p>
      </div>
    </aside>
  );
}
