"use client";

import { useChat } from "@ai-sdk/react";
import type { Project } from "@workspace/compositions/project";
import { compositions } from "@workspace/compositions/registry";
import type { MentionItem } from "@workspace/ui/components/composer";
import { lastAssistantMessageIsCompleteWithToolCalls } from "ai";
import { useEffect, useMemo, useRef, useState } from "react";
import { AgentChat } from "@/components/agent/agent-chat";
import { isAgentVisible } from "@/lib/agent/catalog";
import type { StudioAction } from "../state/reducer";
import { runClientTool } from "./agent-panel/client-tools";
import { EmptyState } from "./agent-panel/empty-state";

type Props = {
  project: Project;
  dispatch: React.Dispatch<StudioAction>;
  onClose: () => void;
  /** The clip currently selected in the timeline/inspector, if any. Lets the
   *  agent target it directly when the user @mentions its composition. */
  selectedClip?: { id: string; compositionId: string } | null;
};

// Cap on how many times the SDK will auto-continue per user message.
// Surgical edits ("add a tweet card") need: listClips → listScenesInCategory
// → getSceneDetails → addClip → updateClipProps — that's 5 tool turns
// before the terminal-tool short-circuit fires on addClip/updateClipProps.
// Set generously so multi-step edits aren't truncated mid-flow; the
// terminal-tool short-circuit ends the loop early on successful builds.
const MAX_AUTO_CONTINUATIONS_PER_USER_MESSAGE = 12;

const TERMINAL_TOOL_TYPES = new Set([
  "tool-buildProject",
  "tool-clearProject",
  "tool-addClip",
  "tool-deleteClip",
  "tool-updateClipProps",
  "tool-updateClipStyle",
  "tool-updateClipDuration",
]);

export function AgentPanel({
  project,
  dispatch,
  onClose,
  selectedClip,
}: Props) {
  // Keep the latest project in a ref so onToolCall (closed over at mount)
  // always sees current clips/ids instead of a stale snapshot. Assigned during
  // render rather than in an effect — the value is only ever read later, in
  // async callbacks, so there's no need to wait for a commit.
  const projectRef = useRef(project);
  projectRef.current = project;

  // The @mention picker offers every agent-visible composition; selecting one
  // inserts `@<id>` into the message. Built once — the registry is static.
  const mentionItems = useMemo<MentionItem[]>(
    () =>
      compositions
        .filter((c) => isAgentVisible(c.id))
        .map((c) => ({ id: c.id, label: c.title, hint: c.category })),
    [],
  );

  // Latest @mention ids + selected clip, read at send time (refs so the
  // memoized chat transport always sees current values).
  const mentionsRef = useRef<string[]>([]);
  const selectedClipRef = useRef(selectedClip ?? null);
  selectedClipRef.current = selectedClip ?? null;

  // Tracks how many times the SDK has auto-continued since the user
  // last sent a message. We compare to the cap inside
  // `sendAutomaticallyWhen` to break runaway loops.
  const autoContinuationCount = useRef(0);

  // Latch: flips true the moment a terminal build/edit lands ok in the
  // CURRENT user turn, and from then on blocks every auto-continuation —
  // even if the build scrolled out of the last message. Once it's built the
  // turn is over; the closing recap is synthesized in MessageBubble, not
  // generated by the model. Reset on each send().
  const builtThisTurn = useRef(false);

  const {
    messages,
    sendMessage,
    status,
    stop,
    error,
    regenerate,
    addToolResult,
  } = useChat({
    sendAutomaticallyWhen: (args) => {
      const ready = lastAssistantMessageIsCompleteWithToolCalls(args);
      if (!ready) return false;

      // Hard stop: a terminal build/edit already landed earlier in this
      // turn. The goal is done — refuse every further continuation so the
      // model can't drift into an open-ended polish loop (transitions,
      // effects) and burn turns toward the cap.
      if (builtThisTurn.current) return false;

      // Terminal-tool short-circuit: the last assistant message includes a
      // successful build (or clear/edit) result — that IS the final action,
      // so stop. We do NOT grant a continuation for a summary turn:
      // gpt-5-mini almost always skips it (it spends its words on the
      // opener), so the turn just burns a call on an empty response. The
      // closing recap is synthesized deterministically in MessageBubble from
      // the build result instead. Latch `builtThisTurn` so the rule still
      // holds if the build scrolls out of the last message.
      const lastMsg = args.messages[args.messages.length - 1];
      if (lastMsg?.role === "assistant") {
        const hasTerminalResult = lastMsg.parts.some((p) => {
          if (!TERMINAL_TOOL_TYPES.has(p.type)) return false;
          const out = (p as { output?: unknown }).output;
          return (
            typeof out === "object" &&
            out !== null &&
            (out as { ok?: unknown }).ok === true
          );
        });
        if (hasTerminalResult) {
          builtThisTurn.current = true;
          return false;
        }
      }

      if (
        autoContinuationCount.current >= MAX_AUTO_CONTINUATIONS_PER_USER_MESSAGE
      ) {
        return false;
      }
      autoContinuationCount.current += 1;
      return true;
    },
    onToolCall: async ({ toolCall }) => {
      const name = toolCall.toolName;
      const input = toolCall.input as Record<string, unknown>;
      try {
        const output = runClientTool(name, input, projectRef, dispatch);
        if (output === undefined) return; // server-executed tool, ignore
        await addToolResult({
          tool: name as never,
          toolCallId: toolCall.toolCallId,
          output: output as never,
        });
      } catch (err) {
        await addToolResult({
          tool: name as never,
          toolCallId: toolCall.toolCallId,
          output: {
            error: err instanceof Error ? err.message : String(err),
          } as never,
        });
      }
    },
  });

  const [input, setInput] = useState("");

  const lastMessage = messages[messages.length - 1];
  const lastIsAssistant = lastMessage?.role === "assistant";
  const hasPendingTool =
    lastMessage?.role === "assistant" &&
    lastMessage.parts.some(
      (p) =>
        p.type.startsWith("tool-") &&
        (p as { output?: unknown }).output === undefined,
    );
  const hasSuccessfulTerminal =
    lastMessage?.role === "assistant" &&
    lastMessage.parts.some((p) => {
      if (!TERMINAL_TOOL_TYPES.has(p.type)) return false;
      const out = (p as { output?: unknown }).output;
      return (
        typeof out === "object" &&
        out !== null &&
        (out as { ok?: unknown }).ok === true
      );
    });
  const hasAnyToolCall =
    lastMessage?.role === "assistant" &&
    lastMessage.parts.some((p) => p.type.startsWith("tool-"));
  // Settled = genuinely done: nothing still waiting on a result, and either
  // a terminal build/edit landed or the assistant replied with plain text
  // and never called a tool at all. Anything else — e.g. listClips just
  // resolved but addClip/buildProject hasn't run — means a continuation
  // is about to fire automatically, even though the HTTP response that
  // carried listClips's result has already closed.
  const lastAssistantSettled =
    lastIsAssistant &&
    !hasPendingTool &&
    (hasSuccessfulTerminal || !hasAnyToolCall);

  // A request is on the wire (or about to be).
  const requestInFlight = status === "submitted" || status === "streaming";

  // The gap AFTER an HTTP response carrying a non-terminal tool result
  // closes (status → "ready") but BEFORE the auto-continuation fires.
  // Normally a few ms; if a continuation never comes (cap hit, or
  // `sendAutomaticallyWhen` returns false) the watchdog below releases us.
  const waitingOnContinuation =
    status === "ready" && lastIsAssistant && !lastAssistantSettled;

  // Either of these means "the agent should still be working".
  const busy = requestInFlight || waitingOnContinuation;

  // ONE watchdog across EVERY busy state — both an in-flight stream and the
  // continuation gap. `status` can get stuck at "streaming" (response never
  // cleanly closes) just as easily as it can lie during the gap, so we
  // can't trust it alone in either case. The timer resets on every new
  // streamed part, so an actively-streaming response keeps it disarmed; it
  // only fires after a long stretch of TOTAL silence — a genuinely hung
  // stream or a continuation that never starts. The window is deliberately
  // generous: a reasoning model can legitimately go quiet for several
  // seconds between steps, and a 4s window (the old value) mistook those
  // pauses for a hang and hid the loader mid-build.
  const [forceIdle, setForceIdle] = useState(false);
  const lastActivitySig = useRef<string>("");
  useEffect(() => {
    const sig = messages
      .map((m) => `${m.id}:${m.parts.length}:${JSON.stringify(m.parts).length}`)
      .join("|");
    if (sig !== lastActivitySig.current) {
      lastActivitySig.current = sig;
      setForceIdle(false);
    }
    if (!busy) return;
    const t = setTimeout(() => setForceIdle(true), 15000);
    return () => clearTimeout(t);
  }, [messages, busy]);

  const isBusy = busy && !forceIdle && !error;

  async function send(text: string) {
    const trimmed = text.trim();
    if (!trimmed) return;
    // If a build is still in flight, cancel it before queuing the new
    // message. Without this the new sendMessage call gets dropped by
    // useChat ("can't send while not ready") and the user's input
    // disappears into the void.
    if (isBusy) {
      await stop();
    }
    autoContinuationCount.current = 0;
    builtThisTurn.current = false;
    // Piggyback any @mentioned components + the selected clip so the server can
    // switch into focused-component mode and append the right context. Refs
    // always point at the latest values, so edits show up on the very next send.
    sendMessage(
      { text: trimmed },
      {
        body: {
          mentions: mentionsRef.current,
          selectedClip: selectedClipRef.current,
        },
      },
    );
    mentionsRef.current = [];
    setInput("");
  }

  return (
    <AgentChat
      messages={messages}
      isBusy={isBusy}
      streaming={status === "streaming"}
      error={error}
      input={input}
      onInputChange={setInput}
      onSend={send}
      onStop={() => stop()}
      onRegenerate={() => regenerate()}
      onClose={onClose}
      subtitle="Describe it — it builds the timeline"
      placeholder={
        isBusy
          ? "Compose your next message — Stop to send now…"
          : "Describe the video you want…"
      }
      emptyState={<EmptyState onPick={send} />}
      mentionItems={mentionItems}
      onMentionsChange={(ids) => {
        mentionsRef.current = ids;
      }}
    />
  );
}
