"use client";

import type { Project } from "@workspace/compositions/project";
import JSZip from "jszip";

const REMOTION_VERSION = "4.0.459";

const RENDER_SCRIPT = `// Auto-generated by Motion Studio. Renders the bundled project to
// output.mp4 using @remotion/renderer with all-cores concurrency.
//
// Usage:
//   npm install
//   node render.mjs

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { selectComposition, renderMedia } from "@remotion/renderer";

const here = path.dirname(fileURLToPath(import.meta.url));
const projectPath = path.join(here, "project.json");
const serveUrl = path.join(here, "bundle");
const outPath = path.join(here, "output.mp4");

const project = JSON.parse(fs.readFileSync(projectPath, "utf8"));
// Match the studio's loader: clip durations are optional in JSON and
// fall back to a fixed default if absent. The exported JSON usually
// already has them, but this keeps the script resilient.
for (const clip of project.clips ?? []) {
  if (typeof clip.durationInFrames !== "number" || clip.durationInFrames <= 0) {
    clip.durationInFrames = 90;
  }
}

// Pre-fetch every absolute http(s) URL referenced in the project and inline
// it as a data: URI. The headless Chrome that @remotion/renderer spawns
// refuses to draw cross-origin images onto its capture canvas (canvas
// tainting), and most public CDNs (github.com avatars, twitter pbs, etc.)
// don't return Access-Control-Allow-Origin. Data URIs are same-origin by
// definition.
async function inlineExternalUrls(value) {
  if (typeof value === "string" && /^https?:\\/\\//i.test(value)) {
    try {
      const res = await fetch(value, { redirect: "follow" });
      if (!res.ok) return value;
      const buf = Buffer.from(await res.arrayBuffer());
      const ct = res.headers.get("content-type") || "image/png";
      return \`data:\${ct};base64,\${buf.toString("base64")}\`;
    } catch {
      return value;
    }
  }
  if (Array.isArray(value)) {
    return Promise.all(value.map(inlineExternalUrls));
  }
  if (value && typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) {
      out[k] = await inlineExternalUrls(v);
    }
    return out;
  }
  return value;
}

console.log("[render] inlining external image URLs…");
const inlined = await inlineExternalUrls(project);

const t0 = performance.now();

console.log("[render] selecting composition…");
const composition = await selectComposition({
  serveUrl,
  id: "Project",
  inputProps: inlined,
});

console.log(
  \`[render] starting — \${composition.width}x\${composition.height} @ \${composition.fps}fps, \${composition.durationInFrames} frames\`,
);

let lastPct = -1;
await renderMedia({
  composition,
  serveUrl,
  codec: "h264",
  outputLocation: outPath,
  inputProps: inlined,
  // Sweet spot empirically on Apple Silicon (M4 Pro): "100%" maps to all 12
  // cores including the 4 efficiency ones, which steal cycles without
  // contributing meaningful throughput. Capping at the perf-core count is
  // faster.
  concurrency: Math.max(2, Math.min(os.cpus().length - 2, 10)),
  hardwareAcceleration: "if-possible",
  // angle = Chrome's hardware-accelerated GL via Metal on macOS. Default
  // (null/swangle) is software — ~7× slower. Tested on the studio's
  // sample project: swangle 394s, angle 60s.
  chromiumOptions: { gl: "angle" },
  onProgress: ({ progress, renderedFrames, encodedFrames }) => {
    const pct = Math.floor(progress * 100);
    if (pct > lastPct) {
      lastPct = pct;
      process.stdout.write(
        \`\\r[render] \${pct}% rendered=\${renderedFrames} encoded=\${encodedFrames}      \`,
      );
    }
  },
});

const seconds = ((performance.now() - t0) / 1000).toFixed(2);
const sizeMB = (fs.statSync(outPath).size / 1024 / 1024).toFixed(2);
console.log(\`\\n[render] done in \${seconds}s — wrote \${outPath} (\${sizeMB} MB)\`);
`;

const PACKAGE_JSON = JSON.stringify(
  {
    name: "motion-studio-render",
    version: "0.0.0",
    private: true,
    type: "module",
    scripts: {
      start: "node render.mjs",
    },
    dependencies: {
      "@remotion/renderer": REMOTION_VERSION,
      remotion: REMOTION_VERSION,
    },
    engines: { node: ">=20" },
  },
  null,
  2,
);

const README = `# Motion Studio — local render

This folder is a self-contained renderer for a single Motion Studio project.
It uses [\`@remotion/renderer\`](https://www.remotion.dev/docs/renderer) to
render the included \`project.json\` to \`output.mp4\`, parallelized across
your CPU cores (so it's substantially faster than the in-browser export).

## Requirements

- Node.js 20 or newer
- ~250 MB free disk for the one-time install + a ~100 MB one-time
  download of Chrome Headless Shell on first run

## Run

\`\`\`bash
npm install
node render.mjs
\`\`\`

The first run will:

1. Install \`@remotion/renderer\` and friends (~1–2 min).
2. Download Chrome Headless Shell on demand (~1 min, cached
   in \`~/Library/Caches\` on macOS or \`~/.cache\` on Linux).
3. Render the project to \`output.mp4\` in this folder.

Subsequent runs reuse both, so they start in about a second.

## Files

- \`project.json\` — the exact project state from your studio session.
- \`bundle/\` — a pre-built Remotion bundle of the composition library.
  Do not edit; replace by re-downloading from the studio.
- \`render.mjs\` — the renderer entrypoint. Reads the bundle + project,
  writes \`output.mp4\`. Uses hardware-accelerated GL (\`gl: "angle"\`) and
  caps concurrency at the perf-core count — going wider hurts on Apple
  Silicon because the extra efficiency cores can't keep up. Tweak if you
  need the machine responsive during render.
- \`package.json\` — pinned dependency versions matching the bundle.

## Output

\`output.mp4\` will appear in this folder when the render finishes. Drop it
anywhere you'd drop a normal MP4 (uploads, NLE timelines, social, etc.).
`;

export async function buildExportZip(opts: {
  project: Project;
}): Promise<Blob> {
  const { project } = opts;

  // Fetch the prebuilt Remotion bundle from the studio. ETag-cached so a
  // second download in the same session is near-instant.
  const bundleRes = await fetch("/api/render-bundle");
  if (!bundleRes.ok) {
    throw new Error(
      `Failed to fetch bundle (${bundleRes.status} ${bundleRes.statusText})`,
    );
  }
  const bundleBuf = await bundleRes.arrayBuffer();

  // Unzip the bundle and re-zip it into the user-facing archive alongside
  // their project + render script. (We could nest the inner zip as a file,
  // but flattening saves the user an extra unzip step and matches the
  // README layout.)
  const bundleZip = await JSZip.loadAsync(bundleBuf);

  const zip = new JSZip();
  zip.file("project.json", JSON.stringify(project, null, 2));
  zip.file("render.mjs", RENDER_SCRIPT);
  zip.file("package.json", PACKAGE_JSON);
  zip.file("README.md", README);

  await Promise.all(
    Object.entries(bundleZip.files).map(async ([name, entry]) => {
      if (entry.dir) return;
      const data = await entry.async("uint8array");
      zip.file(name, data);
    }),
  );

  return zip.generateAsync({
    type: "blob",
    mimeType: "application/zip",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
